version: '3'

services:

  db-postgres:
    image: "postgres:13.3"
    container_name: db-postgres
    ports:
      - 5432:5432


    environment:
      - POSTGRES_DB=room
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345

  backend:
    build: ./
    container_name: backend

    environment:
      - DB_SERVER=db-postgres
      - POSTGRES_DB=room
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - 8080:8080
    links:
      - db-postgres

  frontend:
    build: ./frontend/
    container_name: frontend
    ports:
      - 8081:8081
    links:
      - backend