version: '3'

services:

  db-postgres:
    image: "postgres:13.3"
    container_name: db-postgres
    ports:
      - 5432:5432


    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345

  backend:
    build: ./
    container_name: backend

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/room
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - 8080:8080

  frontend:
    build: ./frontend/
    container_name: frontend
    ports:
      - 8081:8081
    links:
      - backend